/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        canvas: 'var(--paper)',
        surface: 'var(--card)',
        'surface-2': 'var(--paper-2)',
        line: 'var(--line)',
        'line-soft': 'var(--line)',
        ink: 'var(--ink)',
        'ink-2': 'var(--ink-2)',
        mute: 'var(--slate)',
        faint: 'var(--slate-light)',
        nav: 'var(--ink)',
        'nav-hover': 'var(--nav-hover)',
        'nav-strong': 'var(--nav-strong)',
        'nav-line': 'var(--nav-line)',
        'nav-ink': 'var(--nav-cream)',
        'nav-hover-ink': 'var(--nav-hover-text)',
        'header-text': 'var(--header-text)',
        'header-muted': 'var(--header-muted)',
        accent: 'var(--brass)',
        'accent-hover': 'var(--brass-dark)',
        'on-brass': 'var(--on-brass)',
        positive: 'var(--good)',
        'positive-soft': 'var(--good-bg)',
        negative: 'var(--bad)',
        'negative-soft': 'var(--bad-bg)',
        'on-bad': 'var(--on-bad)',
        warn: 'var(--warn)',
        'warn-soft': 'var(--warn-bg)',
        neutral: 'var(--neutral-bg)',
      },
      boxShadow: {
        card: 'var(--shadow-card)',
        modal: 'var(--shadow-modal)',
      },
      fontFamily: {
        sans: ['var(--font-inter)', 'Inter', 'sans-serif'],
        display: ['var(--font-fraunces)', 'Fraunces', 'serif'],
        mono: ['var(--font-ibm-plex-mono)', 'IBM Plex Mono', 'monospace'],
      },
    },
  },
}
